export const ROUTING_CASE_MEMORY_TTL_HOURS = 168;
export const ROUTING_CASE_MEMORY_CAPTURE_ACTION =
  "ROUTING_CASE_MEMORY_CANDIDATE_CAPTURED";
export const ROUTING_CASE_MEMORY_ACTIVATION_ACTION =
  "ROUTING_CASE_MEMORY_CASE_ACTIVATED";
