
import * as fs from 'fs';
import * as path from 'path';

const REGISTRY_FILE = path.resolve(__dirname, '../../LANGUAGE_MIGRATION_REGISTRY_FRONTEND.md');

const TRANSLATIONS: Record<string, string> = {
    // === NAVIGATION & SHELL ===
    "Dashboard": "Дашборд",
    "Tasks": "Задачи",
    "Registry": "Реестр",
    "Economy": "Экономика",
    "University": "Университет",
    "School": "Школа",
    "Courses": "Курсы",
    "AI-Ops": "AI-Ops",
    "OFS": "OFS",
    "Personnel": "Персонал",
    "Foundation": "Фундамент",
    "Login": "Вход",
    "Logout": "Выйти",
    "Back": "Назад",
    "Back to Tasks": "Вернуться к задачам",
    "Details": "Подробнее",
    "Profile": "Профиль",
    "Settings": "Настройки",
    "Admin": "Админ",
    "Guest": "Гость",
    "Home": "Главная",
    "Help": "Помощь",
    "Support": "Поддержка",
    "User": "Пользователь",
    "Manager Hub": "Кабинет руководителя",
    "Soft Skills": "Гибкие навыки",
    "AI Советник": "AI Советник",
    "MatrixGin": "MatrixGin",
    "v2.0": "v2.0",

    // === COMMON UI TERMS ===
    "ID": "ID",
    "ID:": "ID:",
    "Name": "Название",
    "Search": "Поиск",
    "Search...": "Поиск...",
    "Filter": "Фильтр",
    "Sort": "Сортировка",
    "Status": "Статус",
    "Status:": "Статус:",
    "Type": "Тип",
    "Action": "Действие",
    "Actions": "Действия",
    "Save": "Сохранить",
    "Cancel": "Отмена",
    "Delete": "Удалить",
    "Edit": "Редактировать",
    "View": "Просмотр",
    "Create": "Создать",
    "Update": "Обновить",
    "Add": "Добавить",
    "Remove": "Удалить",
    "Select": "Выбрать",
    "Select an entity...": "Выберите сущность...",
    "Confirm": "Подтвердить",
    "Submit": "Отправить",
    "Reset": "Сброс",
    "Close": "Закрыть",
    "Loading...": "Загрузка...",
    "Loading": "Загрузка",
    "Error": "Ошибка",
    "Success": "Успех",
    "Warning": "Внимание",
    "Info": "Инфо",
    "Required": "Обязательно",
    "Optional": "Опционально",
    "N/A": "Н/Д",
    "Data unavailable": "Данные недоступны",
    "No Data": "Нет данных",
    "Refresh": "Обновить",
    "Retry": "Повторить",
    "Copy": "Копировать",
    "Copied!": "Скопировано!",
    "Page": "Страница",
    "Page:": "Страница:",
    "of": "из",
    "Next": "Далее",
    "Previous": "Назад",
    "Date": "Дата",
    "Time": "Время",
    "Timestamp (UTC)": "Метка времени (UTC)",
    "Avatar": "Аватар",
    "Email": "Email",
    "Phone": "Телефон",
    "Role": "Роль",
    "Roles": "Роли",
    "Permissions": "Права",
    "Score": "Баллы",
    "Score:": "Баллы:",
    "Result": "Результат",
    "Results": "Результаты",
    "Value": "Значение",
    "Quantity": "Количество",
    "Qty": "Кол-во",
    "Total": "Итого",
    "Description": "Описание",
    "Content": "Содержание",
    "Title": "Заголовок",
    "Priority": "Приоритет",
    "Tags": "Теги",
    "Assignee": "Исполнитель",
    "Owner": "Владелец",
    "Due Date": "Срок",
    "Created At": "Создано",
    "Created": "Создано",
    "Updated At": "Обновлено",
    "Updated": "Обновлено",
    "Yes": "Да",
    "No": "Нет",
    "None": "Нет",
    "All": "Все",
    "Unknown": "Неизвестно",
    "Empty": "Пусто",
    "Overview": "Обзор",
    "Summary": "Сводка",
    "History": "История",
    "Audit History": "История аудита",
    "Comments": "Комментарии",
    "Events": "События",
    "Notifications": "Уведомления",
    "Messages": "Сообщения",

    // === SPECIFIC MODULES ===

    // Economy
    "Wallet": "Кошелек",
    "Transactions": "Транзакции",
    "Transaction History": "История транзакций",
    "Balance": "Баланс",
    "MatrixCoin Balance": "Баланс MatrixCoin",
    "GoldenMatrixCoin Balance": "Баланс GoldenMatrixCoin",
    "Transfer": "Перевод",
    "Purchase": "Покупка",
    "Reward": "Награда",
    "Penalty": "Штраф",
    "Refund": "Возврат",
    "Currency": "Валюта",
    "Amount": "Сумма",
    "Frozen:": "Заморожено:",
    "MC": "MC",
    "GMC": "GMC",
    "View Transaction History": "История транзакций",
    "Failed to load transactions": "Не удалось загрузить транзакции",
    "No transactions found": "Транзакции не найдены",

    // Gamification
    "Level": "Уровень",
    "Level 5": "Уровень 5",
    "Rank": "Ранг",
    "XP": "XP",
    "Achievements": "Достижения",
    "Quests": "Квесты",
    "Active Quests": "Активные квесты",
    "Start Quest": "Начать квест",
    "Abandon": "Отказаться",
    "Rewards:": "Награды:",
    "Progress": "Прогресс",
    "Next Level:": "След. уровень:",
    "Your Achievements": "Ваши достижения",
    "All Achievements": "Все достижения",
    "Loading achievements...": "Загрузка достижений...",
    "Failed to load achievements.": "Ошибка загрузки достижений.",
    "Loading quests...": "Загрузка квестов...",
    "Failed to load quests.": "Ошибка загрузки квестов.",
    "Earned:": "Получено:",
    "Congratulations! You have reached the highest level.": "Поздравляем! Вы достигли максимального уровня.",
    "% towards next level": "% до следующего уровня",

    // Tasks
    "Create Task": "Создать задачу",
    "Create New Task": "Создать новую задачу",
    "Edit Task": "Редактировать задачу",
    "Task Details": "Детали задачи",
    "My Tasks": "Мои задачи",
    "All Tasks": "Все задачи",
    "Assigned to me": "Назначено мне",
    "Created by me": "Создано мной",
    "Blocking": "Блокирующий",
    "Blocking:": "Блокирующий:",
    "To Do": "Нужно сделать",
    "In Progress": "В работе",
    "Review": "Проверка",
    "Done": "Готово",
    "Archived": "Архив",
    "Low": "Низкий",
    "Medium": "Средний",
    "High": "Высокий",
    "Urgent": "Срочный",
    "Due Date (Optional)": "Срок (опционально)",
    "Create your first task": "Создайте первую задачу",
    "Enter task title": "Введите название задачи",
    "Enter task description": "Введите описание задачи",
    "Title *": "Заголовок *",
    "Description *": "Описание *",
    "Task not found": "Задача не найдена",
    "Failed to load tasks. Please try again.": "Ошибка загрузки задач. Повторите попытку.",

    // Registry / Impact
    "Entity": "Сущность",
    "Entities": "Сущности",
    "Source": "Источник",
    "Target": "Цель",
    "Relation": "Связь",
    "Relations": "Связи",
    "Impact": "Влияние",
    "Impacts": "Влияния",
    "Risk": "Риск",
    "Condition": "Условие",
    "Rule": "Правило",
    "Rules": "Правила",
    "Attribute": "Атрибут",
    "Attributes": "Атрибуты",
    "Graph": "Граф",
    "Nodes": "Узлы",
    "Edges": "Ребра",
    "Schema": "Схема",
    "Validation": "Валидация",
    "Entity not found": "Сущность не найдена",
    "Failed to fetch data": "Ошибка получения данных",
    "Failed to load form": "Ошибка загрузки формы",
    "No Form Data": "Нет данных формы",
    "Impact Analysis": "Анализ влияния",
    "Impact Summary": "Сводка влияния",
    "Affected Entities": "Затронутые сущности",
    "View Details": "Подробнее",
    "Confidence Index": "Индекс доверия",
    "Connecting to Core...": "Подключение к ядру...",
    "Failed to fetch AI analysis": "Ошибка получения AI анализа",
    "AI Advisory Mode": "Режим AI-Советника",
    "These recommendations are generated by AI based on the Registry Graph. They are for informational purposes only and do not execute any actions.": "Эти рекомендации сгенерированы AI на основе графа реестра. Они носят информационный характер.",
    "Visual": "Визуальный",
    "Measurement": "Измерение",
    "Functional": "Функциональный",
    "Defects": "Дефекты",
    "Check Impact": "Проверить влияние",
    "Server-Defined View:": "Серверный вид:",
    "Registry Governance Observability": "Наблюдаемость реестра",
    "Visibility Snapshot (Active Rules)": "Снимок видимости (Активные правила)",
    "Current Visibility Rules (Read-Only)": "Текущие правила видимости (Только чтение)",
    "Scope": "Область",
    "Effect": "Эффект",
    "Projection Map (Diagnostic)": "Карта проекции (Диагностика)",
    "Projection Diagnostics": "Диагностика проекции",
    "Entity Type URN": "URN типа сущности",
    "Analyze Projection": "Анализ проекции",
    "Visible Attributes (": "Видимые атрибуты (",
    "Hidden / Pruned (": "Скрытые / Обрезанные (",
    "Policy Simulator (Safe Mode)": "Симулятор политик (Безопасный режим)",
    "Run 'What If' Analysis": "Запустить анализ 'Что если'",
    "Target Entity": "Целевая сущность",
    "Simulate Adding Rule:": "Симуляция правила:",
    "EXCLUDE": "ИСКЛЮЧИТЬ",
    "Simulate Diff": "Симуляция разницы",
    "Added Visibility (Visible -> Hidden?) No, Hidden -> Visible": "Добавлена видимость",
    "Removed Visibility (Visible -> Hidden)": "Убрана видимость",
    "No changes detected": "Изменений не обнаружено",
    "View Snapshot": "Просмотр снимка",
    "Historical Snapshot (Read-Only)": "Исторический снимок",
    "Impact Analysis Preview": "Предпросмотр влияния",
    "READ-ONLY SNAPSHOT": "СНИМОК ТОЛЬКО ДЛЯ ЧТЕНИЯ",
    "Relationships (Snapshot)": "Связи (Снимок)",
    "Register Quality Check": "Проверка качества реестра",

    // OFS / Foundation
    "Structure": "Структура",
    "Function": "Функция",
    "Organization": "Организация",
    "Department": "Департамент",
    "Unit": "Подразделение",
    "Position": "Должность",
    "Instruction": "Инструкция",
    "Regulation": "Регламент",
    "Constitution": "Конституция",
    "Code of Honor": "Кодекс Чести",
    "Golden Standards": "Золотые Стандарты",
    "Corporate Codex": "Корпоративный Кодекс",
    "The Constitution": "Конституция",
    "Golden Standard": "Золотой Стандарт",
    "Role Model (MDR)": "Ролевая Модель (MDR)",
    "Motivation Core": "Ядро Мотивации",
    "Quality": "Качество",
    "Speed": "Скорость",
    "Sales": "Продажи",
    "Team": "Команда",
    "CPK": "ЦПК",
    "Universe": "Вселенная",
    "Checks": "Проверки",
    "Coach": "Коуч",
    "Consequences": "Последствия",
    "CPK Alignment": "Соответствие ЦПК",
    "CPK Hierarchy": "Иерархия ЦПК",
    "CPK Owners": "Владельцы ЦПК",
    "Use mouse to rotate • Read-Only": "Используйте мышь для вращения • Только чтение",
    "Current Status:": "Текущий статус:",
    "Date:": "Дата:",
    "Days active:": "Дней активно:",
    "Foundational Immersion": "Фундаментальное погружение",
    "Sales Excellence Academy": "Академия Продаж",
    "PhotoCraft Academy": "Академия PhotoCraft",
    "Service & Customer Care Academy": "Академия Сервиса",
    "Values & Culture Academy": "Академия Ценностей",
    "Soft Skills Academy": "Академия Soft Skills",
    "Equipment & Tech Academy": "Академия Технологий",
    "Leadership & Management Academy": "Академия Лидерства",

    // Messages
    "Operation successful": "Операция успешна",
    "Operation Failed": "Ошибка операции",
    "Operation failed": "Ошибка операции",
    "Entity Created": "Сущность создана",
    "Entity Updated": "Сущность обновлена",
    "Access Denied": "Доступ запрещен",
    "Access denied": "Доступ запрещен",
    "Access Restricted": "Доступ ограничен",
    "Internal server error": "Внутренняя ошибка сервера",
    "Please provide a mandatory rejection comment:": "Укажите обязательный комментарий отказа:",
    "You have declined the Foundation.": "Вы отклонили Фундамент.",
    "Logging out...": "Выход...",
    "Welcome to the Matrix, Colleague.": "Добро пожаловать в Матрицу, Коллега.",
    "Foundation Accepted": "Фундамент принят",
    "I Decline (Exit System)": "Отказываюсь (Выход)",
    "I confirm that I have read the Foundation Blocks and I ACCEPT these rules without reservation.": "Подтверждаю прочтение Блоков Фундамента и ПРИНИМАЮ правила.",
    "This decision is binding and recorded in the immutable Foundation Audit Log.": "Решение обязательно и записано в Аудит-лог.",
    "The Economy is merit-based.": "Экономика основана на заслугах.",
    "Performance is measured by Results (MDR), not effort.": "Результат важнее усилий (MDR).",
    "Violating the Codex (Fraud, Theft, Ethics) leads to immediate termination.": "Нарушение Кодекса ведет к увольнению.",
    "You acknowledge that:": "Вы признаете, что:",
    "By accepting, you confirm that you have read, understood, and agree to abide by the": "Принимая, вы соглашаетесь соблюдать",
    "Final Decision": "Финальное решение",
    "Are you sure? Declining means you cannot access the University or Economy. You will be logged out.": "Уверены? Отказ ограничит доступ. Вы будете разлогинены.",
    "This action is recorded in the immutable audit log.": "Действие записано в лог.",
    "By clicking, you confirm you have read and understood this block.": "Нажимая, вы подтверждаете прочтение блока.",
    "I Understand & Accept": "Понимаю и Принимаю",
    "Meaning": "Значение",
    "Block": "Блок",
    "Invalid Block ID": "Неверный ID Блока",
    "Welcome to the Corporate University.": "Добро пожаловать в Университет.",
    "Before accessing": "Перед доступом к",
    "Applied Knowledge": "Прикладным Знаниям",
    "and": "и",
    ",\r\n                you must complete the": ",\r\n                необходимо завершить",
    "Begin Immersion": "Начать погружение",
    "Sign in to access the system": "Войдите в систему",
    "Email address": "Email",
    "Password": "Пароль",
    "No new improvement suggestions at the moment.": "Нет предложений по улучшению.",
    "Target: Active listening once per month per mentee.": "Цель: Активное слушание раз в месяц.",
    "No tasks found": "Задачи не найдены",
    "No comments yet": "Нет комментариев",
    "Field \"": "Поле \"",
    "\" not found in entity card": "\" не найдено в карточке",
    "Relation definition not found for:": "Связь не найдена для:",
    "No view definition found": "Вид не найден",

    // Specific Uncategorized
    "PDF, JPG, PNG до 10MB": "PDF, JPG, PNG до 10МБ",
    "Employee ID:": "ID Сотрудника:",
    "Должность ID *": "ID Должности *",
    "Департамент ID *": "ID Департамента *",
    "Target Pattern": "Целевой паттерн",
    "Role Condition": "Условие роли",
    "Simulated Role": "Симулированная роль",
    "Lifecycle (Drafts)": "ЖЦ (Черновики)",
    "Signal Heat": "Тепловая карта сигналов",
    "Scenario Diff": "Разница сценариев",
    "Lens": "Линза",
    "Overlays": "Наложения",
    "LOADING GRAPH DATA...": "ЗАГРУЗКА ДАННЫХ...",
    "INSUFFICIENT DATA": "НЕДОСТАТОЧНО ДАННЫХ",
    "Focus Mode": "Фокус-режим",
    "OWNS": "ВЛАДЕЕТ",
    "KPI": "KPI",
    "KPI:": "KPI:",
    "SLA": "SLA",
    "NPS": "NPS",
    "URL": "URL",
    "uptime": "uptime",
    "Leaderboard": "Таблица лидеров",
};

console.log(`Processing registry: ${REGISTRY_FILE}`);
const content = fs.readFileSync(REGISTRY_FILE, 'utf-8');
const lines = content.split('\n');
const outputLines: string[] = [];
let currentFrom = "";

for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (trimmed.startsWith('FROM:')) {
        const match = trimmed.match(/^FROM: "(.*)"$/);
        if (match) {
            currentFrom = match[1];
        }
        outputLines.push(line);
    } else if (trimmed.startsWith('TO:')) {
        // Try to match exact translation
        if (currentFrom && TRANSLATIONS[currentFrom]) {
            const translated = TRANSLATIONS[currentFrom];
            // Escape quotes in translation if necessary, but simplistically:
            outputLines.push(`TO:   "${translated}"`);
        } else if (currentFrom) {
            // Auto-detect if already Russian
            if (/[а-яА-ЯёЁ]/.test(currentFrom) && !/[a-zA-Z]/.test(currentFrom)) {
                outputLines.push(`TO:   "${currentFrom}"`);
            } else {
                outputLines.push(line);
            }
        } else {
            outputLines.push(line);
        }
        currentFrom = "";
    } else {
        outputLines.push(line);
    }
}

fs.writeFileSync(REGISTRY_FILE, outputLines.join('\n'));
console.log("Registry updated with available translations.");
