
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  inn: 'inn',
  type: 'type',
  riskLevel: 'riskLevel',
  companyId: 'companyId',
  holdingId: 'holdingId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HoldingScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MachineryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  brand: 'brand',
  serialNumber: 'serialNumber',
  type: 'type',
  status: 'status',
  idempotencyKey: 'idempotencyKey',
  companyId: 'companyId',
  clientId: 'clientId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  confirmedByUserId: 'confirmedByUserId',
  confirmedAt: 'confirmedAt',
  archivedAt: 'archivedAt',
  rejectionReason: 'rejectionReason'
};

exports.Prisma.StockItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  status: 'status',
  quantity: 'quantity',
  unit: 'unit',
  idempotencyKey: 'idempotencyKey',
  companyId: 'companyId',
  clientId: 'clientId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  confirmedByUserId: 'confirmedByUserId',
  confirmedAt: 'confirmedAt',
  archivedAt: 'archivedAt',
  rejectionReason: 'rejectionReason'
};

exports.Prisma.StockTransactionScalarFieldEnum = {
  id: 'id',
  itemId: 'itemId',
  type: 'type',
  amount: 'amount',
  date: 'date',
  userId: 'userId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  role: 'role',
  phone: 'phone',
  telegramId: 'telegramId',
  emailVerified: 'emailVerified',
  emailVerificationToken: 'emailVerificationToken',
  emailVerificationExpiresAt: 'emailVerificationExpiresAt',
  companyId: 'companyId',
  clientId: 'clientId',
  accessLevel: 'accessLevel',
  invitedBy: 'invitedBy',
  invitedAt: 'invitedAt',
  activatedAt: 'activatedAt',
  demoExpiresAt: 'demoExpiresAt',
  coreUserId: 'coreUserId',
  coreWalletId: 'coreWalletId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  token: 'token',
  shortCode: 'shortCode',
  email: 'email',
  telegramId: 'telegramId',
  inviterId: 'inviterId',
  inviteeId: 'inviteeId',
  role: 'role',
  accessLevel: 'accessLevel',
  companyId: 'companyId',
  clientId: 'clientId',
  status: 'status',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  acceptedAt: 'acceptedAt',
  activationIp: 'activationIp',
  activationUserAgent: 'activationUserAgent'
};

exports.Prisma.FieldScalarFieldEnum = {
  id: 'id',
  cadastreNumber: 'cadastreNumber',
  name: 'name',
  area: 'area',
  coordinates: 'coordinates',
  centroid: 'centroid',
  soilType: 'soilType',
  status: 'status',
  clientId: 'clientId',
  companyId: 'companyId',
  coreObjectId: 'coreObjectId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RapeseedScalarFieldEnum = {
  id: 'id',
  name: 'name',
  variety: 'variety',
  reproduction: 'reproduction',
  type: 'type',
  oilContent: 'oilContent',
  erucicAcid: 'erucicAcid',
  glucosinolates: 'glucosinolates',
  vegetationPeriod: 'vegetationPeriod',
  sowingNormMin: 'sowingNormMin',
  sowingNormMax: 'sowingNormMax',
  sowingDepthMin: 'sowingDepthMin',
  sowingDepthMax: 'sowingDepthMax',
  version: 'version',
  isLatest: 'isLatest',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RapeseedHistoryScalarFieldEnum = {
  id: 'id',
  rapeseedId: 'rapeseedId',
  version: 'version',
  changeReason: 'changeReason',
  changedBy: 'changedBy',
  snapshot: 'snapshot',
  createdAt: 'createdAt'
};

exports.Prisma.SeasonScalarFieldEnum = {
  id: 'id',
  year: 'year',
  status: 'status',
  fieldId: 'fieldId',
  cropId: 'cropId',
  rapeseedId: 'rapeseedId',
  technologyCardId: 'technologyCardId',
  expectedYield: 'expectedYield',
  actualYield: 'actualYield',
  isLocked: 'isLocked',
  lockedAt: 'lockedAt',
  lockedBy: 'lockedBy',
  startDate: 'startDate',
  endDate: 'endDate',
  coreProcessId: 'coreProcessId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  currentStageId: 'currentStageId'
};

exports.Prisma.SeasonSnapshotScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  year: 'year',
  status: 'status',
  fieldId: 'fieldId',
  rapeseedId: 'rapeseedId',
  expectedYield: 'expectedYield',
  actualYield: 'actualYield',
  startDate: 'startDate',
  endDate: 'endDate',
  snapshotData: 'snapshotData',
  companyId: 'companyId',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.AuditFailureScalarFieldEnum = {
  id: 'id',
  event: 'event',
  userId: 'userId',
  metadata: 'metadata',
  error: 'error',
  attempt: 'attempt',
  createdAt: 'createdAt'
};

exports.Prisma.SeasonStageProgressScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  stageId: 'stageId',
  completedAt: 'completedAt',
  metadata: 'metadata'
};

exports.Prisma.SeasonHistoryScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  action: 'action',
  changes: 'changes',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.BusinessRuleScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  description: 'description',
  params: 'params',
  isActive: 'isActive',
  severity: 'severity',
  companyId: 'companyId',
  version: 'version',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TechnologyCardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TechnologyCardOperationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sequence: 'sequence',
  technologyCardId: 'technologyCardId',
  stageId: 'stageId',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TechnologyCardResourceScalarFieldEnum = {
  id: 'id',
  operationId: 'operationId',
  type: 'type',
  name: 'name',
  dosage: 'dosage',
  unit: 'unit',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  seasonId: 'seasonId',
  operationId: 'operationId',
  fieldId: 'fieldId',
  assigneeId: 'assigneeId',
  responsibleId: 'responsibleId',
  plannedDate: 'plannedDate',
  slaExpiration: 'slaExpiration',
  completedAt: 'completedAt',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaskResourceActualScalarFieldEnum = {
  id: 'id',
  taskId: 'taskId',
  type: 'type',
  name: 'name',
  amount: 'amount',
  unit: 'unit',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmployeeProfileScalarFieldEnum = {
  id: 'id',
  externalId: 'externalId',
  userId: 'userId',
  orgUnitId: 'orgUnitId',
  roleId: 'roleId',
  requiredRoleCompetencyRef: 'requiredRoleCompetencyRef',
  companyId: 'companyId',
  holdingId: 'holdingId',
  clientId: 'clientId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HrOnboardingPlanScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  stages: 'stages',
  progress: 'progress',
  startDate: 'startDate',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HrSupportCaseScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  type: 'type',
  subject: 'subject',
  status: 'status',
  createdAt: 'createdAt',
  closedAt: 'closedAt'
};

exports.Prisma.RoleDefinitionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  userId: 'userId',
  ip: 'ip',
  userAgent: 'userAgent',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.ApiUsageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  ip: 'ip',
  action: 'action',
  count: 'count',
  date: 'date'
};

exports.Prisma.MemoryEntryScalarFieldEnum = {
  id: 'id',
  content: 'content',
  metadata: 'metadata',
  companyId: 'companyId',
  memoryType: 'memoryType',
  source: 'source',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.DealScalarFieldEnum = {
  id: 'id',
  name: 'name',
  stage: 'stage',
  amount: 'amount',
  probability: 'probability',
  expectedDate: 'expectedDate',
  clientId: 'clientId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ScoreCardScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  financialHealth: 'financialHealth',
  agroPotential: 'agroPotential',
  reliability: 'reliability',
  ltvPrediction: 'ltvPrediction',
  companyId: 'companyId',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.ContractScalarFieldEnum = {
  id: 'id',
  number: 'number',
  type: 'type',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  amount: 'amount',
  clientId: 'clientId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TechMapScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  soilType: 'soilType',
  moisture: 'moisture',
  precursor: 'precursor',
  status: 'status',
  version: 'version',
  isLatest: 'isLatest',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MapStageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sequence: 'sequence',
  techMapId: 'techMapId',
  aplStageId: 'aplStageId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MapOperationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  mapStageId: 'mapStageId',
  plannedStartTime: 'plannedStartTime',
  plannedEndTime: 'plannedEndTime',
  durationHours: 'durationHours',
  requiredMachineryType: 'requiredMachineryType',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MapResourceScalarFieldEnum = {
  id: 'id',
  mapOperationId: 'mapOperationId',
  type: 'type',
  name: 'name',
  amount: 'amount',
  unit: 'unit',
  costPerUnit: 'costPerUnit',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DeviationReviewScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  stageId: 'stageId',
  deviationSummary: 'deviationSummary',
  aiImpactAssessment: 'aiImpactAssessment',
  techConclusion: 'techConclusion',
  proposedActions: 'proposedActions',
  telegramThreadId: 'telegramThreadId',
  clientResponseStatus: 'clientResponseStatus',
  clientComment: 'clientComment',
  clientRespondedAt: 'clientRespondedAt',
  responsibilityMode: 'responsibilityMode',
  slaExpiration: 'slaExpiration',
  liabilityShiftStatus: 'liabilityShiftStatus',
  status: 'status',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CmrDecisionScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  action: 'action',
  reason: 'reason',
  actor: 'actor',
  confidenceLevel: 'confidenceLevel',
  alternatives: 'alternatives',
  companyId: 'companyId',
  createdAt: 'createdAt',
  userId: 'userId'
};

exports.Prisma.CmrRiskScalarFieldEnum = {
  id: 'id',
  seasonId: 'seasonId',
  type: 'type',
  description: 'description',
  probability: 'probability',
  impact: 'impact',
  controllability: 'controllability',
  liabilityMode: 'liabilityMode',
  mitigationPlan: 'mitigationPlan',
  deviationReviewId: 'deviationReviewId',
  status: 'status',
  taskId: 'taskId',
  observationId: 'observationId',
  responsibleId: 'responsibleId',
  insuranceId: 'insuranceId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InsuranceCoverageScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  insurer: 'insurer',
  type: 'type',
  status: 'status',
  insuredAmount: 'insuredAmount',
  deductible: 'deductible',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FieldObservationScalarFieldEnum = {
  id: 'id',
  type: 'type',
  intent: 'intent',
  integrityStatus: 'integrityStatus',
  content: 'content',
  photoUrl: 'photoUrl',
  voiceUrl: 'voiceUrl',
  telemetryJson: 'telemetryJson',
  coordinates: 'coordinates',
  taskId: 'taskId',
  fieldId: 'fieldId',
  seasonId: 'seasonId',
  deviationReviewId: 'deviationReviewId',
  authorId: 'authorId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OkrCycleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  startDate: 'startDate',
  endDate: 'endDate',
  status: 'status',
  companyId: 'companyId'
};

exports.Prisma.ObjectiveScalarFieldEnum = {
  id: 'id',
  title: 'title',
  cycleId: 'cycleId',
  ownerId: 'ownerId',
  progress: 'progress',
  createdAt: 'createdAt'
};

exports.Prisma.KeyResultScalarFieldEnum = {
  id: 'id',
  title: 'title',
  objectiveId: 'objectiveId',
  targetValue: 'targetValue',
  currentValue: 'currentValue',
  metricSource: 'metricSource',
  lastUpdated: 'lastUpdated'
};

exports.Prisma.HrKPIIndicatorScalarFieldEnum = {
  id: 'id',
  externalKey: 'externalKey',
  title: 'title',
  value: 'value',
  capturedAt: 'capturedAt',
  companyId: 'companyId'
};

exports.Prisma.HrRecognitionEventScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  type: 'type',
  message: 'message',
  createdAt: 'createdAt'
};

exports.Prisma.HrRewardEventScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  type: 'type',
  amount: 'amount',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.PulseSurveyScalarFieldEnum = {
  id: 'id',
  title: 'title',
  questions: 'questions',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.SurveyResponseScalarFieldEnum = {
  id: 'id',
  pulseSurveyId: 'pulseSurveyId',
  respondentId: 'respondentId',
  answers: 'answers',
  submittedAt: 'submittedAt'
};

exports.Prisma.HumanAssessmentSnapshotScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  burnoutRisk: 'burnoutRisk',
  engagementLevel: 'engagementLevel',
  ethicalAlignment: 'ethicalAlignment',
  controllability: 'controllability',
  confidenceLevel: 'confidenceLevel',
  validFrom: 'validFrom',
  validTo: 'validTo',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.PersonalCompetencyStateScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  competencyId: 'competencyId',
  level: 'level',
  updatedAt: 'updatedAt'
};

exports.Prisma.HrDevelopmentPlanScalarFieldEnum = {
  id: 'id',
  employeeId: 'employeeId',
  createdAt: 'createdAt'
};

exports.Prisma.HrDevelopmentActionScalarFieldEnum = {
  id: 'id',
  planId: 'planId',
  type: 'type',
  description: 'description',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.EconomicEventScalarFieldEnum = {
  id: 'id',
  type: 'type',
  amount: 'amount',
  currency: 'currency',
  metadata: 'metadata',
  fieldId: 'fieldId',
  seasonId: 'seasonId',
  employeeId: 'employeeId',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.LedgerEntryScalarFieldEnum = {
  id: 'id',
  economicEventId: 'economicEventId',
  amount: 'amount',
  type: 'type',
  accountCode: 'accountCode',
  companyId: 'companyId',
  isImmutable: 'isImmutable',
  createdAt: 'createdAt'
};

exports.Prisma.CashAccountScalarFieldEnum = {
  id: 'id',
  name: 'name',
  balance: 'balance',
  currency: 'currency',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BudgetScalarFieldEnum = {
  id: 'id',
  name: 'name',
  limit: 'limit',
  consumed: 'consumed',
  remaining: 'remaining',
  status: 'status',
  periodStart: 'periodStart',
  periodEnd: 'periodEnd',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BudgetLineScalarFieldEnum = {
  id: 'id',
  budgetId: 'budgetId',
  category: 'category',
  limit: 'limit',
  consumed: 'consumed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RegulatoryBodyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  type: 'type',
  scope: 'scope',
  powers: 'powers',
  sanctions: 'sanctions',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LegalDocumentScalarFieldEnum = {
  id: 'id',
  title: 'title',
  externalId: 'externalId',
  type: 'type',
  sourceUrl: 'sourceUrl',
  effectiveDate: 'effectiveDate',
  expirationDate: 'expirationDate',
  version: 'version',
  regulatorId: 'regulatorId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LegalNormScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  paragraph: 'paragraph',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LegalRequirementScalarFieldEnum = {
  id: 'id',
  normId: 'normId',
  summary: 'summary',
  type: 'type',
  status: 'status',
  targetType: 'targetType',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ObligationScalarFieldEnum = {
  id: 'id',
  requirementId: 'requirementId',
  description: 'description',
  dueDate: 'dueDate',
  ownerId: 'ownerId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SanctionScalarFieldEnum = {
  id: 'id',
  obligationId: 'obligationId',
  type: 'type',
  amount: 'amount',
  description: 'description',
  createdAt: 'createdAt'
};

exports.Prisma.ComplianceCheckScalarFieldEnum = {
  id: 'id',
  requirementId: 'requirementId',
  status: 'status',
  observation: 'observation',
  confidenceLevel: 'confidenceLevel',
  checkedAgainstVersion: 'checkedAgainstVersion',
  companyId: 'companyId',
  checkedAt: 'checkedAt'
};

exports.Prisma.GrInteractionScalarFieldEnum = {
  id: 'id',
  regulatorId: 'regulatorId',
  type: 'type',
  subject: 'subject',
  content: 'content',
  date: 'date',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.PolicySignalScalarFieldEnum = {
  id: 'id',
  subject: 'subject',
  description: 'description',
  probability: 'probability',
  impactLevel: 'impactLevel',
  expectedDate: 'expectedDate',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.ExternalLegalFeedScalarFieldEnum = {
  id: 'id',
  documentId: 'documentId',
  source: 'source',
  externalRef: 'externalRef',
  rawContent: 'rawContent',
  lastSync: 'lastSync'
};

exports.Prisma.ResearchProgramScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  name: 'name',
  objective: 'objective',
  hypothesis: 'hypothesis',
  status: 'status',
  createdAt: 'createdAt',
  archivedAt: 'archivedAt'
};

exports.Prisma.ExperimentScalarFieldEnum = {
  id: 'id',
  programId: 'programId',
  name: 'name',
  type: 'type',
  state: 'state',
  activeProtocolId: 'activeProtocolId',
  createdAt: 'createdAt'
};

exports.Prisma.ProtocolScalarFieldEnum = {
  id: 'id',
  experimentId: 'experimentId',
  version: 'version',
  methodology: 'methodology',
  variables: 'variables',
  successCriteria: 'successCriteria',
  status: 'status',
  approvedAt: 'approvedAt',
  approvedBy: 'approvedBy',
  createdAt: 'createdAt'
};

exports.Prisma.TrialScalarFieldEnum = {
  id: 'id',
  experimentId: 'experimentId',
  location: 'location',
  conditions: 'conditions',
  startDate: 'startDate',
  endDate: 'endDate',
  deviations: 'deviations',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MeasurementScalarFieldEnum = {
  id: 'id',
  trialId: 'trialId',
  variable: 'variable',
  value: 'value',
  unit: 'unit',
  measuredAt: 'measuredAt',
  locked: 'locked'
};

exports.Prisma.ResearchResultScalarFieldEnum = {
  id: 'id',
  experimentId: 'experimentId',
  analysis: 'analysis',
  significance: 'significance',
  createdAt: 'createdAt'
};

exports.Prisma.ResearchConclusionScalarFieldEnum = {
  id: 'id',
  experimentId: 'experimentId',
  conclusion: 'conclusion',
  applicability: 'applicability',
  limitations: 'limitations',
  createdAt: 'createdAt'
};

exports.Prisma.KnowledgeNodeScalarFieldEnum = {
  id: 'id',
  type: 'type',
  label: 'label',
  source: 'source',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.KnowledgeEdgeScalarFieldEnum = {
  id: 'id',
  fromNodeId: 'fromNodeId',
  toNodeId: 'toNodeId',
  relation: 'relation',
  confidence: 'confidence',
  source: 'source',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.VisionObservationScalarFieldEnum = {
  id: 'id',
  source: 'source',
  assetId: 'assetId',
  timestamp: 'timestamp',
  modality: 'modality',
  rawFeatures: 'rawFeatures',
  metadata: 'metadata',
  confidence: 'confidence',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.SatelliteObservationScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  timestamp: 'timestamp',
  indexType: 'indexType',
  value: 'value',
  source: 'source',
  resolution: 'resolution',
  cloudCoverage: 'cloudCoverage',
  tileId: 'tileId',
  confidence: 'confidence',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.RiskSignalScalarFieldEnum = {
  id: 'id',
  source: 'source',
  severity: 'severity',
  reasonCode: 'reasonCode',
  description: 'description',
  referenceType: 'referenceType',
  referenceId: 'referenceId',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.RiskAssessmentScalarFieldEnum = {
  id: 'id',
  targetType: 'targetType',
  targetId: 'targetId',
  verdict: 'verdict',
  score: 'score',
  explanation: 'explanation',
  companyId: 'companyId',
  assessedAt: 'assessedAt'
};

exports.Prisma.RiskStateHistoryScalarFieldEnum = {
  id: 'id',
  targetType: 'targetType',
  targetId: 'targetId',
  fromState: 'fromState',
  toState: 'toState',
  reason: 'reason',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.DecisionRecordScalarFieldEnum = {
  id: 'id',
  actionType: 'actionType',
  targetId: 'targetId',
  riskVerdict: 'riskVerdict',
  riskState: 'riskState',
  explanation: 'explanation',
  traceId: 'traceId',
  companyId: 'companyId',
  decidedAt: 'decidedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.ClientType = exports.$Enums.ClientType = {
  FARMER: 'FARMER',
  DEALER: 'DEALER',
  HOLDING: 'HOLDING',
  PARTNER: 'PARTNER'
};

exports.RiskLevel = exports.$Enums.RiskLevel = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

exports.MachineryType = exports.$Enums.MachineryType = {
  TRACTOR: 'TRACTOR',
  SPRAYER: 'SPRAYER',
  HARVESTER: 'HARVESTER',
  ATTACHMENT: 'ATTACHMENT',
  TRUCK: 'TRUCK'
};

exports.AssetStatus = exports.$Enums.AssetStatus = {
  ACTIVE: 'ACTIVE',
  REPAIR: 'REPAIR',
  OFFLINE: 'OFFLINE',
  PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
  REJECTED: 'REJECTED',
  ARCHIVED: 'ARCHIVED'
};

exports.StockItemType = exports.$Enums.StockItemType = {
  CHEMICAL: 'CHEMICAL',
  FERTILIZER: 'FERTILIZER',
  SEED: 'SEED',
  FUEL: 'FUEL'
};

exports.StockTransactionType = exports.$Enums.StockTransactionType = {
  PROCUREMENT: 'PROCUREMENT',
  CONSUMPTION: 'CONSUMPTION',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.UserRole = exports.$Enums.UserRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  AGRONOMIST: 'AGRONOMIST',
  FIELD_WORKER: 'FIELD_WORKER',
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  USER: 'USER'
};

exports.UserAccessLevel = exports.$Enums.UserAccessLevel = {
  DEMO: 'DEMO',
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  TERMINATED: 'TERMINATED'
};

exports.InvitationStatus = exports.$Enums.InvitationStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
};

exports.SoilType = exports.$Enums.SoilType = {
  CHERNOZEM: 'CHERNOZEM',
  LOAM: 'LOAM',
  SANDY: 'SANDY',
  CLAY: 'CLAY',
  PODZOLIC: 'PODZOLIC',
  SODDY: 'SODDY',
  GRAY_FOREST: 'GRAY_FOREST',
  CHESTNUT: 'CHESTNUT'
};

exports.FieldStatus = exports.$Enums.FieldStatus = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  IN_PROCESSING: 'IN_PROCESSING'
};

exports.RapeseedType = exports.$Enums.RapeseedType = {
  WINTER: 'WINTER',
  SPRING: 'SPRING'
};

exports.SeasonStatus = exports.$Enums.SeasonStatus = {
  PLANNING: 'PLANNING',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.RuleSeverity = exports.$Enums.RuleSeverity = {
  ERROR: 'ERROR',
  WARNING: 'WARNING',
  INFO: 'INFO'
};

exports.TaskStatus = exports.$Enums.TaskStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.LifecycleStatus = exports.$Enums.LifecycleStatus = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  TERMINATED: 'TERMINATED'
};

exports.DealStage = exports.$Enums.DealStage = {
  LEAD: 'LEAD',
  QUALIFICATION: 'QUALIFICATION',
  OFFER: 'OFFER',
  CONTRACT: 'CONTRACT',
  CLOSED_WON: 'CLOSED_WON',
  CLOSED_LOST: 'CLOSED_LOST'
};

exports.TechMapStatus = exports.$Enums.TechMapStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED'
};

exports.ClientResponseStatus = exports.$Enums.ClientResponseStatus = {
  PENDING: 'PENDING',
  AGREED: 'AGREED',
  DISAGREED: 'DISAGREED',
  IGNORED: 'IGNORED'
};

exports.ResponsibilityMode = exports.$Enums.ResponsibilityMode = {
  SHARED: 'SHARED',
  CLIENT_ONLY: 'CLIENT_ONLY',
  CONSULTANT_ONLY: 'CONSULTANT_ONLY',
  LIABILITY_SUSPENDED: 'LIABILITY_SUSPENDED'
};

exports.ReviewStatus = exports.$Enums.ReviewStatus = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  ESCALATED: 'ESCALATED'
};

exports.ConfidenceLevel = exports.$Enums.ConfidenceLevel = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

exports.RiskType = exports.$Enums.RiskType = {
  AGRONOMIC: 'AGRONOMIC',
  CLIMATE: 'CLIMATE',
  OPERATIONAL: 'OPERATIONAL',
  REGULATORY: 'REGULATORY',
  MARKET: 'MARKET'
};

exports.Controllability = exports.$Enums.Controllability = {
  CONSULTANT: 'CONSULTANT',
  CLIENT: 'CLIENT',
  SHARED: 'SHARED',
  FORCE_MAJEURE: 'FORCE_MAJEURE'
};

exports.LiabilityMode = exports.$Enums.LiabilityMode = {
  CONSULTANT_ONLY: 'CONSULTANT_ONLY',
  CLIENT_ONLY: 'CLIENT_ONLY',
  SHARED: 'SHARED',
  INSURABLE: 'INSURABLE',
  LIABILITY_SUSPENDED: 'LIABILITY_SUSPENDED'
};

exports.InsuranceType = exports.$Enums.InsuranceType = {
  YIELD_LOSS: 'YIELD_LOSS',
  WEATHER_INDEX: 'WEATHER_INDEX',
  REGULATORY: 'REGULATORY'
};

exports.ObservationType = exports.$Enums.ObservationType = {
  PHOTO: 'PHOTO',
  GEO_WALK: 'GEO_WALK',
  VOICE_NOTE: 'VOICE_NOTE',
  CALL_LOG: 'CALL_LOG',
  MEASUREMENT: 'MEASUREMENT',
  SOS_SIGNAL: 'SOS_SIGNAL'
};

exports.ObservationIntent = exports.$Enums.ObservationIntent = {
  MONITORING: 'MONITORING',
  INCIDENT: 'INCIDENT',
  CONSULTATION: 'CONSULTATION',
  CALL: 'CALL',
  CONFIRMATION: 'CONFIRMATION',
  DELAY: 'DELAY'
};

exports.IntegrityStatus = exports.$Enums.IntegrityStatus = {
  STRONG_EVIDENCE: 'STRONG_EVIDENCE',
  WEAK_EVIDENCE: 'WEAK_EVIDENCE',
  NO_EVIDENCE: 'NO_EVIDENCE'
};

exports.EconomicEventType = exports.$Enums.EconomicEventType = {
  COST_INCURRED: 'COST_INCURRED',
  REVENUE_RECOGNIZED: 'REVENUE_RECOGNIZED',
  OBLIGATION_CREATED: 'OBLIGATION_CREATED',
  OBLIGATION_SETTLED: 'OBLIGATION_SETTLED',
  RESERVE_ALLOCATED: 'RESERVE_ALLOCATED',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.BudgetStatus = exports.$Enums.BudgetStatus = {
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  EXHAUSTED: 'EXHAUSTED',
  BLOCKED: 'BLOCKED',
  CLOSED: 'CLOSED'
};

exports.RegulatorType = exports.$Enums.RegulatorType = {
  FISCAL: 'FISCAL',
  SUPERVISORY: 'SUPERVISORY',
  EXECUTIVE: 'EXECUTIVE',
  LEGISLATIVE: 'LEGISLATIVE',
  ASSOCIATION: 'ASSOCIATION'
};

exports.DocumentType = exports.$Enums.DocumentType = {
  STATUTORY_LAW: 'STATUTORY_LAW',
  REGULATION: 'REGULATION',
  TECHNICAL_NORM: 'TECHNICAL_NORM',
  CONTRACT: 'CONTRACT',
  JUDICIAL_ACT: 'JUDICIAL_ACT'
};

exports.RequirementType = exports.$Enums.RequirementType = {
  MANDATORY: 'MANDATORY',
  RESTRICTIVE: 'RESTRICTIVE',
  PERMISSIVE: 'PERMISSIVE',
  PROHIBITIVE: 'PROHIBITIVE'
};

exports.ComplianceStatus = exports.$Enums.ComplianceStatus = {
  COMPLIANT: 'COMPLIANT',
  AT_RISK: 'AT_RISK',
  VIOLATED: 'VIOLATED',
  UNKNOWN: 'UNKNOWN'
};

exports.ImpactTargetType = exports.$Enums.ImpactTargetType = {
  CONTRACT: 'CONTRACT',
  SEASON: 'SEASON',
  TRANSACTION: 'TRANSACTION',
  EMPLOYEE: 'EMPLOYEE',
  LAND_PARCEL: 'LAND_PARCEL',
  RND_EXPERIMENT: 'RND_EXPERIMENT',
  RND_PROTOCOL: 'RND_PROTOCOL'
};

exports.ObligationStatus = exports.$Enums.ObligationStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  OVERDUE: 'OVERDUE',
  WAIVED: 'WAIVED'
};

exports.SanctionType = exports.$Enums.SanctionType = {
  PENALTY: 'PENALTY',
  FINE: 'FINE',
  LICENSE_REVOCATION: 'LICENSE_REVOCATION',
  SUSPENSION: 'SUSPENSION',
  REPUTATIONAL: 'REPUTATIONAL'
};

exports.InteractionType = exports.$Enums.InteractionType = {
  MEETING: 'MEETING',
  INSPECTION: 'INSPECTION',
  LETTER: 'LETTER',
  WORKING_GROUP: 'WORKING_GROUP'
};

exports.ImpactLevel = exports.$Enums.ImpactLevel = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

exports.ProgramStatus = exports.$Enums.ProgramStatus = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  SUSPENDED: 'SUSPENDED',
  ARCHIVED: 'ARCHIVED'
};

exports.ExperimentType = exports.$Enums.ExperimentType = {
  DRUG: 'DRUG',
  TECH: 'TECH',
  METHOD: 'METHOD',
  COMPARATIVE: 'COMPARATIVE',
  FIELD: 'FIELD',
  METRIC: 'METRIC'
};

exports.ExperimentState = exports.$Enums.ExperimentState = {
  IDEA: 'IDEA',
  HYPOTHESIS_DEFINED: 'HYPOTHESIS_DEFINED',
  PROTOCOL_DRAFT: 'PROTOCOL_DRAFT',
  SCIENTIFIC_REVIEW: 'SCIENTIFIC_REVIEW',
  LEGAL_APPROVAL: 'LEGAL_APPROVAL',
  EXPERIMENT_APPROVED: 'EXPERIMENT_APPROVED',
  RUNNING: 'RUNNING',
  DATA_COLLECTION: 'DATA_COLLECTION',
  ANALYSIS: 'ANALYSIS',
  PEER_REVIEW: 'PEER_REVIEW',
  CONCLUSION_ISSUED: 'CONCLUSION_ISSUED',
  ARCHIVED: 'ARCHIVED'
};

exports.ProtocolStatus = exports.$Enums.ProtocolStatus = {
  DRAFT: 'DRAFT',
  REVIEW: 'REVIEW',
  APPROVED: 'APPROVED',
  SUPERSEDED: 'SUPERSEDED'
};

exports.KnowledgeNodeType = exports.$Enums.KnowledgeNodeType = {
  CONCEPT: 'CONCEPT',
  ENTITY: 'ENTITY',
  METRIC: 'METRIC',
  DOCUMENT: 'DOCUMENT'
};

exports.KnowledgeNodeSource = exports.$Enums.KnowledgeNodeSource = {
  MANUAL: 'MANUAL',
  INGESTION: 'INGESTION',
  AI: 'AI'
};

exports.KnowledgeEdgeRelation = exports.$Enums.KnowledgeEdgeRelation = {
  IMPLEMENTS: 'IMPLEMENTS',
  DEPENDS_ON: 'DEPENDS_ON',
  MEASURED_BY: 'MEASURED_BY',
  MEASURES: 'MEASURES',
  REFERENCES: 'REFERENCES'
};

exports.KnowledgeEdgeSource = exports.$Enums.KnowledgeEdgeSource = {
  MANUAL: 'MANUAL',
  INGESTION: 'INGESTION',
  AI: 'AI'
};

exports.VisionObservationSource = exports.$Enums.VisionObservationSource = {
  SATELLITE: 'SATELLITE',
  DRONE: 'DRONE',
  PHOTO: 'PHOTO'
};

exports.VisionObservationModality = exports.$Enums.VisionObservationModality = {
  RGB: 'RGB',
  MULTISPECTRAL: 'MULTISPECTRAL'
};

exports.SatelliteIndexType = exports.$Enums.SatelliteIndexType = {
  NDVI: 'NDVI',
  NDRE: 'NDRE'
};

exports.SatelliteSource = exports.$Enums.SatelliteSource = {
  SENTINEL2: 'SENTINEL2',
  LANDSAT8: 'LANDSAT8',
  LANDSAT9: 'LANDSAT9'
};

exports.RiskSource = exports.$Enums.RiskSource = {
  LEGAL: 'LEGAL',
  RND: 'RND',
  OPS: 'OPS',
  FINANCE: 'FINANCE'
};

exports.RiskSeverity = exports.$Enums.RiskSeverity = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

exports.RiskReferenceType = exports.$Enums.RiskReferenceType = {
  EXPERIMENT: 'EXPERIMENT',
  REQUIREMENT: 'REQUIREMENT',
  TASK: 'TASK',
  TRANSACTION: 'TRANSACTION'
};

exports.RiskTargetType = exports.$Enums.RiskTargetType = {
  ACTION: 'ACTION',
  TECHNOLOGY: 'TECHNOLOGY',
  CLIENT: 'CLIENT',
  SEASON: 'SEASON'
};

exports.RiskVerdict = exports.$Enums.RiskVerdict = {
  ALLOWED: 'ALLOWED',
  CONDITIONAL: 'CONDITIONAL',
  RESTRICTED: 'RESTRICTED',
  BLOCKED: 'BLOCKED'
};

exports.RiskFsmState = exports.$Enums.RiskFsmState = {
  CLEAR: 'CLEAR',
  OBSERVED: 'OBSERVED',
  ELEVATED: 'ELEVATED',
  CRITICAL: 'CRITICAL',
  BLOCKED: 'BLOCKED',
  RESOLVED: 'RESOLVED'
};

exports.Prisma.ModelName = {
  Company: 'Company',
  Client: 'Client',
  Holding: 'Holding',
  Machinery: 'Machinery',
  StockItem: 'StockItem',
  StockTransaction: 'StockTransaction',
  User: 'User',
  Invitation: 'Invitation',
  Field: 'Field',
  Rapeseed: 'Rapeseed',
  RapeseedHistory: 'RapeseedHistory',
  Season: 'Season',
  SeasonSnapshot: 'SeasonSnapshot',
  AuditFailure: 'AuditFailure',
  SeasonStageProgress: 'SeasonStageProgress',
  SeasonHistory: 'SeasonHistory',
  BusinessRule: 'BusinessRule',
  TechnologyCard: 'TechnologyCard',
  TechnologyCardOperation: 'TechnologyCardOperation',
  TechnologyCardResource: 'TechnologyCardResource',
  Task: 'Task',
  TaskResourceActual: 'TaskResourceActual',
  EmployeeProfile: 'EmployeeProfile',
  HrOnboardingPlan: 'HrOnboardingPlan',
  HrSupportCase: 'HrSupportCase',
  RoleDefinition: 'RoleDefinition',
  AuditLog: 'AuditLog',
  ApiUsage: 'ApiUsage',
  MemoryEntry: 'MemoryEntry',
  Deal: 'Deal',
  ScoreCard: 'ScoreCard',
  Contract: 'Contract',
  TechMap: 'TechMap',
  MapStage: 'MapStage',
  MapOperation: 'MapOperation',
  MapResource: 'MapResource',
  DeviationReview: 'DeviationReview',
  CmrDecision: 'CmrDecision',
  CmrRisk: 'CmrRisk',
  InsuranceCoverage: 'InsuranceCoverage',
  FieldObservation: 'FieldObservation',
  OkrCycle: 'OkrCycle',
  Objective: 'Objective',
  KeyResult: 'KeyResult',
  HrKPIIndicator: 'HrKPIIndicator',
  HrRecognitionEvent: 'HrRecognitionEvent',
  HrRewardEvent: 'HrRewardEvent',
  PulseSurvey: 'PulseSurvey',
  SurveyResponse: 'SurveyResponse',
  HumanAssessmentSnapshot: 'HumanAssessmentSnapshot',
  PersonalCompetencyState: 'PersonalCompetencyState',
  HrDevelopmentPlan: 'HrDevelopmentPlan',
  HrDevelopmentAction: 'HrDevelopmentAction',
  EconomicEvent: 'EconomicEvent',
  LedgerEntry: 'LedgerEntry',
  CashAccount: 'CashAccount',
  Budget: 'Budget',
  BudgetLine: 'BudgetLine',
  RegulatoryBody: 'RegulatoryBody',
  LegalDocument: 'LegalDocument',
  LegalNorm: 'LegalNorm',
  LegalRequirement: 'LegalRequirement',
  Obligation: 'Obligation',
  Sanction: 'Sanction',
  ComplianceCheck: 'ComplianceCheck',
  GrInteraction: 'GrInteraction',
  PolicySignal: 'PolicySignal',
  ExternalLegalFeed: 'ExternalLegalFeed',
  ResearchProgram: 'ResearchProgram',
  Experiment: 'Experiment',
  Protocol: 'Protocol',
  Trial: 'Trial',
  Measurement: 'Measurement',
  ResearchResult: 'ResearchResult',
  ResearchConclusion: 'ResearchConclusion',
  KnowledgeNode: 'KnowledgeNode',
  KnowledgeEdge: 'KnowledgeEdge',
  VisionObservation: 'VisionObservation',
  SatelliteObservation: 'SatelliteObservation',
  RiskSignal: 'RiskSignal',
  RiskAssessment: 'RiskAssessment',
  RiskStateHistory: 'RiskStateHistory',
  DecisionRecord: 'DecisionRecord'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
