export enum AgriculturalAuditEvent {
    // --- Rapeseed ---
    RAPESEED_CREATED = 'RAPESEED_CREATED',
    RAPESEED_UPDATED = 'RAPESEED_UPDATED',
    RAPESEED_PARAMETERS_CHANGED = 'RAPESEED_PARAMETERS_CHANGED', // Детальное изменение агро-параметров
    RAPESEED_VARIETY_CHANGED = 'RAPESEED_VARIETY_CHANGED',
    RAPESEED_OIL_CONTENT_UPDATED = 'RAPESEED_OIL_CONTENT_UPDATED',

    // --- Seasons ---
    SEASON_CREATED = 'SEASON_CREATED',
    SEASON_UPDATED = 'SEASON_UPDATED',
    SEASON_COMPLETED = 'SEASON_COMPLETED',
    SEASON_LOCKED = 'SEASON_LOCKED',
    SEASON_SNAPSHOT_CREATED = 'SEASON_SNAPSHOT_CREATED',

    RAPESEED_SEASON_CREATED = 'RAPESEED_SEASON_CREATED',
    RAPESEED_SEASON_UPDATED = 'RAPESEED_SEASON_UPDATED',
    RAPESEED_SEASON_COMPLETED = 'RAPESEED_SEASON_COMPLETED',
    RAPESEED_SEASON_UPDATE_ATTEMPT_ON_LOCKED = 'RAPESEED_SEASON_UPDATE_ATTEMPT_ON_LOCKED',
    RAPESEED_YIELD_RECORDED = 'RAPESEED_YIELD_RECORDED',

    // --- Yield ---
    YIELD_RECORDED = 'YIELD_RECORDED',
    YIELD_UPDATED = 'YIELD_UPDATED',

    // --- Business Rules ---
    RAPESEED_ROTATION_VIOLATION = 'RAPESEED_ROTATION_VIOLATION',
    BUSINESS_RULE_OVERRIDE = 'BUSINESS_RULE_OVERRIDE',

    // --- Bulk & Utils ---
    RAPESEED_VERSION_ROLLBACK = 'RAPESEED_VERSION_ROLLBACK',
    RAPESEED_BULK_IMPORT = 'RAPESEED_BULK_IMPORT',
    RAPESEED_EXPORT = 'RAPESEED_EXPORT',

    // --- System ---
    CACHE_INVALIDATED = 'CACHE_INVALIDATED',
}
